# The model arguments
model_name: UNet3D
model_kwargs:
  in_channels: 1
  out_channels: 3
  initial_num_fmaps: 12
  fmap_growth: 5
  scale_factor: [[1, 3, 3], [1, 3, 3], [1, 3, 3]]
  final_activation: Sigmoid
  conv_type_key: 'vanilla'

training_optimizer_kwargs:
  method: Adam
  lr: 0.0001
  weight_decay: 0.0005

devices:
  - 0
  - 1
